In [1]:
import pandas as pd
import json
from sqlalchemy import create_engine, text

In [2]:
# Carga de datos desde un archivo CSV en un DataFrame
df_csv = pd.read_csv('/Users/israeljuarezjimenez/Documents/BDA/practica_5/empleado.csv', delimiter=';', quotechar='"', encoding='latin1')

print(df_csv.head())

print('-------------------------------------------------------------')
print(df_csv.tail())
print('-------------------------------------------------------------')
print(df_csv.shape)
print('-------------------------------------------------------------')
print(df_csv.info())
print('-------------------------------------------------------------')
print(df_csv.describe())
print('-------------------------------------------------------------')
print(df_csv['salario'])
print('-------------------------------------------------------------')
print("Salario medio:", df_csv['salario'].mean())
print('-------------------------------------------------------------')

   empno   nombre         puesto     jefe  salario  comision  departamento
0   1232    López       Vendedor   Huerta  12500.0    5000.0        Ventas
1   1233  Morales  Administrador   Huesca  29750.0       0.0  Contabilidad
2   1236  Rosillo  Administrador   Huesca  30000.0       0.0   Operaciones
3   1237   Segura       Analista  Morales  29750.0       0.0  Contabilidad
4   1238   Huesca     Presidente      NaN  50000.0       0.0   Operaciones
-------------------------------------------------------------
    empno     nombre     puesto     jefe  salario  comision  departamento
6    1240    Benitez  Asistente   Segura  11000.0       0.0  Contabilidad
7    1241     Corona  Asistente   Huerta   9500.0       0.0        Ventas
8    1242  Domínguez   Analista  Morales  30000.0       0.0  Contabilidad
9    1248   Portales  Asistente  Rosillo  13000.0       0.0   Operaciones
10   1249     Moreno  Asistente   Huesca  13000.0       0.0  Contabilidad
-------------------------------------------------------------
(11, 7)
-------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   empno         11 non-null     int64
 1   nombre        11 non-null     object
 2   puesto        11 non-null     object
 3   jefe          10 non-null     object
 4   salario       11 non-null     float64
 5   comision      11 non-null     float64
 6   departamento  11 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 748.0+ bytes
None
-------------------------------------------------------------
             empno       salario     comision
count    11.000000     11.000000    11.000000
mean   1239.545455  22136.363636   636.363636
std       5.391913  12690.234255  1566.698904
min    1232.000000   9500.000000     0.000000
25%    1236.500000  12750.000000     0.000000
50%    1239.000000  15000.000000     0.000000
75%    1241.500000  29875.000000     0.000000
max    1249.000000  50000.000000  5000.000000
-------------------------------------------------------------
0     12500.0
1     29750.0
2     30000.0
3     29750.0
4     50000.0
5     15000.0
6     11000.0
7      9500.0
8     30000.0
9     13000.0
10    13000.0
Name: salario, dtype: float64
-------------------------------------------------------------
Salario medio: 22136.363636363636
-------------------------------------------------------------

In [3]:
# Carga de datos desde un archivo JSON en un DataFrame 
ruta_archivo = '/Users/israeljuarezjimenez/Documents/BDA/practica_5/empleado.json'
with open(ruta_archivo, 'r') as archivo:
    datos_json = json.load(archivo)
df_json = pd.DataFrame(datos_json)
df_json

   empno     nombre  jefe fecha_contratacion  salario  deptno
0   1232      López  1235         2001-01-01  12500.0      30
1   1233    Morales  1238         2014-05-20  29750.0      20
2   1224    Santana  1235         2001-09-29  28500.0      40
3   1225      Ramos  1238         2009-05-16  24500.0      40
4   1227     Segura  1233         2005-05-05  29750.0      20
5   1228  Hernández     0         2000-01-01  50000.0      10
6   1229    Fuentes  1235         2006-02-24  15000.0      40
7   1248   Portales  1236         2016-02-14  13000.0      10

In [4]:
# Carga de datos desde un archivo TXT en un DataFrame 
archivo = '/Users/israeljuarezjimenez/Documents/BDA/practica_5/empleados.txt'

def read_file(file_path, encoding='utf-8'):
    try:
        with open(file_path, 'r', encoding=encoding) as file:
            content = file.read()
    except UnicodeDecodeError:
        with open(file_path, 'r', encoding='latin-1') as file:
            content = file.read()
    return content

content = read_file(archivo)

blocks = content.strip().split('\n\n')

def process_block(block):
    employee_data = {}
    for line in block.split('\n'):
        if ': ' in line:
            key, value = line.split(': ', 1)
            employee_data[key.strip()] = value.strip()
    return employee_data

data = [process_block(block) for block in blocks if block.strip()]

df_txt = pd.DataFrame(data)

print(df_txt)

    empleado sueldo fecha de contratación  departamento comisiones
0  Fernandez  12000            23/12/2001    Ingeniería       2000
1  Rodriguez  14000            13/08/2002    Ingeniería       3000
2  Salamanca  14000            14/07/2007      Sistemas       4000
3  Fernandez  13000            19/02/2010      Sistemas       1000
4     Juaréz  14000            23/12/2001  Contabilidad       3000

In [5]:
# Carga de datos desde un archivo SQL en un DataFrame 
# Establecer conexión a la base de datos MySQL
bd_nombre = 'Empleados_bd'
usuario = 'root'
contrasena = 'Juarez31'
host = 'localhost'
puerto = '3306'
cadena_conexion = f'mysql+pymysql://{usuario}:{contrasena}@{host}:{puerto}/{bd_nombre}'
engine = create_engine(cadena_conexion)

# Leer y ejecutar un script SQL desde un archivo
name_file = '/Users/israeljuarezjimenez/Documents/BDA/practica_5/empleados.sql'
with open(name_file, 'r', encoding='utf-8') as file:
    sql_script = file.read()

commands = sql_script.split(';')
with engine.begin() as connection:
    for command in commands:
        if command.strip():
            connection.execute(text(command))

# Cargar datos de tablas específicas en DataFrames y mostrarlos
tablas = ['departamento', 'empleado', 'proyecto', 'empleado_proyecto']
dataframes = {}
for tabla in tablas:
    query = f"SELECT * FROM {tabla};"
    df = pd.read_sql_query(query, engine)
    dataframes[tabla] = df
    print(df)
    print("\n")

# Mostrar el DataFrame de empleados específicamente
df_sql = dataframes['empleado']
print("DataFrame de Empleados:")
print(df_sql)

   deptno         nombre       ubicacion
0      10   Contabilidad  Aguascalientes
1      30  Investigación       Guadalara
2      20         Ventas            CDMX
3      40    Operaciones        Tlaxcala


    empno     nombre         puesto    jefe fecha_contratacion  salario  \
0    1230   González      Asistente  1242.0         2010-10-12   8000.0
1    1231      Ramos       Vendedor  1235.0         2018-02-13  16000.0
2    1232      López       Vendedor  1235.0         2001-01-01  12500.0
3    1233    Morales  Administrador  1238.0         2014-05-20  29750.0
4    1234     Aldama       Vendedor  1235.0         2001-09-29  28500.0
5    1235     Huerta  Administrador  1238.0         2009-05-16  24500.0
6    1236    Rosillo  Administrador  1238.0         2017-03-13  30000.0
7    1237     Segura       Analista  1233.0         2005-05-05  29750.0
8    1238     Huesca     Presidente     NaN         2000-01-01  50000.0
9    1239    Rosales       Vendedor  1235.0         2006-02-24  15000.0
10   1240    Benitez      Asistente  1237.0         2008-09-16  11000.0
11   1241     Corona      Asistente  1235.0         2008-08-23   9500.0
12   1242  Domínguez       Analista  1233.0         2017-07-16  30000.0
13   1248   Portales      Asistente  1236.0         2016-02-14  13000.0

    comision  deptno
0        NaN      20
1     3000.0      30
2     5000.0      30
3        NaN      20
4        NaN      30
5        NaN      30
6        NaN      10
7        NaN      20
8        NaN      10
9     2000.0      30
10       NaN      20
11       NaN      30
12       NaN      20
13       NaN      10


   prono nombre       ubicacion  deptno
0   1001     P1        Tlaxcala      20
1   1004     P4            CDMX      30
2   1005     P5            CDMX      30
3   1008     P6  Aguascalientes      30


   empno  prono  horas
0   1231   1004     15
1   1231   1005     12
2   1232   1004     10
3   1232   1008      8
4   1234   1001     16
5   1234   1006     15
6   1234   1008      5
7   1239   1005      6
8   1248   1001      4


DataFrame de Empleados:
    empno     nombre         puesto    jefe fecha_contratacion  salario  \
0    1230   González      Asistente  1242.0         2010-10-12   8000.0
1    1231      Ramos       Vendedor  1235.0         2018-02-13  16000.0
2    1232      López       Vendedor  1235.0         2001-01-01  12500.0
3    1233    Morales  Administrador  1238.0         2014-05-20  29750.0
4    1234     Aldama       Vendedor  1235.0         2001-09-29  28500.0
5    1235     Huerta  Administrador  1238.0         2009-05-16  24500.0
6    1236    Rosillo  Administrador  1238.0         2017-03-13  30000.0
7    1237     Segura       Analista  1233.0         2005-05-05  29750.0
8    1238     Huesca     Presidente     NaN         2000-01-01  50000.0
9    1239    Rosales       Vendedor  1235.0         2006-02-24  15000.0
10   1240    Benitez      Asistente  1237.0         2008-09-16  11000.0
11   1241     Corona      Asistente  1235.0         2008-08-23   9500.0
12   1242  Domínguez       Analista  1233.0         2017-07-16  30000.0
13   1248   Portales      Asistente  1236.0         2016-02-14  13000.0

    comision  deptno
0        NaN      20
1     3000.0      30
2     5000.0      30
3        NaN      20
4        NaN      30
5        NaN      30
6        NaN      10
7        NaN      20
8        NaN      10
9     2000.0      30
10       NaN      20
11       NaN      30
12       NaN      20
13       NaN      10

In [6]:
# Renombrar columnas en DataFrame cargado desde CSV para estandarizar los nombres de las columnas
df_csv = df_csv.rename(columns={'empno': 'Empleado', 'nombre': 'Nombre', 'puesto': 'Puesto', 
                                'jefe': 'Jefe', 'salario': 'Salario', 'comision': 'Comisión',
                                'departamento': 'Departamento'})
# Renombrar columnas en DataFrame cargado desde JSON para estandarizar los nombres de las columnas
df_json = df_json.rename(columns={'empno': 'Empleado', 'nombre': 'Nombre', 'jefe': 'JefeNo', 
                                  'fecha_contratacion': 'Fecha_Contratacion', 'salario': 'Salario', 
                                  'deptno': 'DeptNo'})
# Renombrar columnas en DataFrame cargado desde TXT para estandarizar los nombres de las columnas
df_txt = df_txt.rename(columns={'empleado': 'Nombre', 'sueldo': 'Salario', 'fecha de contratación': 'Fecha_Contratacion',
                                'departamento': 'Departamento', 'comisiones': 'Comisión'})
# Renombrar columnas en DataFrame cargado desde SQL para estandarizar los nombres de las columnas
df_sql = df_sql.rename(columns={'empno': 'Empleado', 'nombre': 'Nombre', 'puesto': 'Puesto', 'jefe': 'JefeNo',
                                'fecha_contratacion': 'Fecha_Contratacion', 'salario': 'Salario', 
                                'comision': 'Comisión', 'deptno': 'DeptNo'})
print('----------------------------------------------------------------------------')
print(df_csv)
print('----------------------------------------------------------------------------')
print(df_json)
print('----------------------------------------------------------------------------')
print(df_txt)
print('----------------------------------------------------------------------------')
print(df_sql)

----------------------------------------------------------------------------
    Empleado     Nombre         Puesto     Jefe  Salario  Comisión  \
0       1232      López       Vendedor   Huerta  12500.0    5000.0
1       1233    Morales  Administrador   Huesca  29750.0       0.0
2       1236    Rosillo  Administrador   Huesca  30000.0       0.0
3       1237     Segura       Analista  Morales  29750.0       0.0
4       1238     Huesca     Presidente      NaN  50000.0       0.0
5       1239    Rosales       Vendedor   Huerta  15000.0    2000.0
6       1240    Benitez      Asistente   Segura  11000.0       0.0
7       1241     Corona      Asistente   Huerta   9500.0       0.0
8       1242  Domínguez       Analista  Morales  30000.0       0.0
9       1248   Portales      Asistente  Rosillo  13000.0       0.0
10      1249     Moreno      Asistente   Huesca  13000.0       0.0

    Departamento
0         Ventas
1   Contabilidad
2    Operaciones
3   Contabilidad
4    Operaciones
5         Ventas
6   Contabilidad
7         Ventas
8   Contabilidad
9    Operaciones
10  Contabilidad
----------------------------------------------------------------------------
   Empleado     Nombre  JefeNo Fecha_Contratacion  Salario  DeptNo
0      1232      López    1235         2001-01-01  12500.0      30
1      1233    Morales    1238         2014-05-20  29750.0      20
2      1224    Santana    1235         2001-09-29  28500.0      40
3      1225      Ramos    1238         2009-05-16  24500.0      40
4      1227     Segura    1233         2005-05-05  29750.0      20
5      1228  Hernández       0         2000-01-01  50000.0      10
6      1229    Fuentes    1235         2006-02-24  15000.0      40
7      1248   Portales    1236         2016-02-14  13000.0      10
----------------------------------------------------------------------------
      Nombre Salario Fecha_Contratacion  Departamento Comisión
0  Fernandez   12000         23/12/2001    Ingeniería     2000
1  Rodriguez   14000         13/08/2002    Ingeniería     3000
2  Salamanca   14000         14/07/2007      Sistemas     4000
3  Fernandez   13000         19/02/2010      Sistemas     1000
4     Juaréz   14000         23/12/2001  Contabilidad     3000
----------------------------------------------------------------------------
    Empleado     Nombre         Puesto  JefeNo Fecha_Contratacion  Salario  \
0       1230   González      Asistente  1242.0         2010-10-12   8000.0
1       1231      Ramos       Vendedor  1235.0         2018-02-13  16000.0
2       1232      López       Vendedor  1235.0         2001-01-01  12500.0
3       1233    Morales  Administrador  1238.0         2014-05-20  29750.0
4       1234     Aldama       Vendedor  1235.0         2001-09-29  28500.0
5       1235     Huerta  Administrador  1238.0         2009-05-16  24500.0
6       1236    Rosillo  Administrador  1238.0         2017-03-13  30000.0
7       1237     Segura       Analista  1233.0         2005-05-05  29750.0
8       1238     Huesca     Presidente     NaN         2000-01-01  50000.0
9       1239    Rosales       Vendedor  1235.0         2006-02-24  15000.0
10      1240    Benitez      Asistente  1237.0         2008-09-16  11000.0
11      1241     Corona      Asistente  1235.0         2008-08-23   9500.0
12      1242  Domínguez       Analista  1233.0         2017-07-16  30000.0
13      1248   Portales      Asistente  1236.0         2016-02-14  13000.0

    Comisión  DeptNo
0        NaN      20
1     3000.0      30
2     5000.0      30
3        NaN      20
4        NaN      30
5        NaN      30
6        NaN      10
7        NaN      20
8        NaN      10
9     2000.0      30
10       NaN      20
11       NaN      30
12       NaN      20
13       NaN      10

In [7]:
# Concatenar múltiples DataFrames en uno solo
# Los DataFrames df_sql, df_json, df_txt, y df_csv se combinan en df_general
df_general = pd.concat([df_sql,df_json,df_txt,df_csv], ignore_index=True)

In [8]:
df_general

,Empleado,Nombre,Puesto,JefeNo,Fecha_Contratacion,Salario,Comisión,DeptNo,Departamento,Jefe
0,1230.0,González,Asistente,1242.0,2010-10-12,8000.0,NaN,20.0,NaN,NaN
1,1231.0,Ramos,Vendedor,1235.0,2018-02-13,16000.0,3000.0,30.0,NaN,NaN
2,1232.0,López,Vendedor,1235.0,2001-01-01,12500.0,5000.0,30.0,NaN,NaN
3,1233.0,Morales,Administrador,1238.0,2014-05-20,29750.0,NaN,20.0,NaN,NaN
4,1234.0,Aldama,Vendedor,1235.0,2001-09-29,28500.0,NaN,30.0,NaN,NaN
5,1235.0,Huerta,Administrador,1238.0,2009-05-16,24500.0,NaN,30.0,NaN,NaN
6,1236.0,Rosillo,Administrador,1238.0,2017-03-13,30000.0,NaN,10.0,NaN,NaN
7,1237.0,Segura,Analista,1233.0,2005-05-05,29750.0,NaN,20.0,NaN,NaN
8,1238.0,Huesca,Presidente,NaN,2000-01-01,50000.0,NaN,10.0,NaN,NaN
9,1239.0,Rosales,Vendedor,1235.0,2006-02-24,15000.0,2000.0,30.0,NaN,NaN
10,1240.0,Benitez,Asistente,1237.0,2008-09-16,11000.0,NaN,20.0,NaN,NaN
11,1241.0,Corona,Asistente,1235.0,2008-08-23,9500.0,NaN,30.0,NaN,NaN
12,1242.0,Domínguez,Analista,1233.0,2017-07-16,30000.0,NaN,20.0,NaN,NaN
13,1248.0,Portales,Asistente,1236.0,2016-02-14,13000.0,NaN,10.0,NaN,NaN
14,1232.0,López,NaN,1235.0,2001-01-01,12500.0,NaN,30.0,NaN,NaN
15,1233.0,Morales,NaN,1238.0,2014-05-20,29750.0,NaN,20.0,NaN,NaN
16,1224.0,Santana,NaN,1235.0,2001-09-29,28500.0,NaN,40.0,NaN,NaN
17,1225.0,Ramos,NaN,1238.0,2009-05-16,24500.0,NaN,40.0,NaN,NaN
18,1227.0,Segura,NaN,1233.0,2005-05-05,29750.0,NaN,20.0,NaN,NaN
19,1228.0,Hernández,NaN,0.0,2000-01-01,50000.0,NaN,10.0,NaN,NaN
20,1229.0,Fuentes,NaN,1235.0,2006-02-24,15000.0,NaN,40.0,NaN,NaN
21,1248.0,Portales,NaN,1236.0,2016-02-14,13000.0,NaN,10.0,NaN,NaN
22,NaN,Fernandez,NaN,NaN,23/12/2001,12000,2000,NaN,Ingeniería,NaN
23,NaN,Rodriguez,NaN,NaN,13/08/2002,14000,3000,NaN,Ingeniería,NaN
24,NaN,Salamanca,NaN,NaN,14/07/2007,14000,4000,NaN,Sistemas,NaN
25,NaN,Fernandez,NaN,NaN,19/02/2010,13000,1000,NaN,Sistemas,NaN
26,NaN,Juaréz,NaN,NaN,23/12/2001,14000,3000,NaN,Contabilidad,NaN
27,1232.0,López,Vendedor,NaN,NaN,12500.0,5000.0,NaN,Ventas,Huerta
28,1233.0,Morales,Administrador,NaN,NaN,29750.0,0.0,NaN,Contabilidad,Huesca
29,1236.0,Rosillo,Administrador,NaN,NaN,30000.0,0.0,NaN,Operaciones,Huesca
30,1237.0,Segura,Analista,NaN,NaN,29750.0,0.0,NaN,Contabilidad,Morales
31,1238.0,Huesca,Presidente,NaN,NaN,50000.0,0.0,NaN,Operaciones,NaN
32,1239.0,Rosales,Vendedor,NaN,NaN,15000.0,2000.0,NaN,Ventas,Huerta
33,1240.0,Benitez,Asistente,NaN,NaN,11000.0,0.0,NaN,Contabilidad,Segura
34,1241.0,Corona,Asistente,NaN,NaN,9500.0,0.0,NaN,Ventas,Huerta
35,1242.0,Domínguez,Analista,NaN,NaN,30000.0,0.0,NaN,Contabilidad,Morales
36,1248.0,Portales,Asistente,NaN,NaN,13000.0,0.0,NaN,Operaciones,Rosillo
37,1249.0,Moreno,Asistente,NaN,NaN,13000.0,0.0,NaN,Contabilidad,Huesca

In [9]:
# Limpieza de datos: Rellenar valores faltantes
df_general['Empleado'] = df_general['Empleado'].ffill() 
df_general['Jefe'] = df_general.groupby('Empleado')['Jefe'].ffill().bfill()
df_general['Salario'] = df_general.groupby('Empleado')['Salario'].ffill().bfill()
df_general['Comisión'] = df_general.groupby('Empleado')['Comisión'].ffill().bfill()
df_general['Departamento'] = df_general.groupby('Empleado')['Departamento'].ffill().bfill()
df_general['JefeNo'] = df_general.groupby('Empleado')['JefeNo'].ffill().bfill()
df_general['DeptNo'] = df_general.groupby('Empleado')['DeptNo'].ffill().bfill()

# Relleno de valores faltantes para la fecha de contratación
df_general['Fecha_Contratacion'] = df_general.groupby('Empleado')['Fecha_Contratacion'].ffill().bfill()

# Transformación: Estandarización de formatos de fecha (Si se reintroduce 'Fecha_Contratacion')
df_general['Fecha_Contratacion'] = pd.to_datetime(df_general['Fecha_Contratacion'], errors='coerce')

# Transformación: Eliminación de registros duplicados, conservando el último registro de cada empleado
df_general = df_general.drop_duplicates(subset='Empleado', keep='last')

# Mostrar las primeras filas del DataFrame limpio
df_general

,Empleado,Nombre,Puesto,JefeNo,Fecha_Contratacion,Salario,Comisión,DeptNo,Departamento,Jefe
0,1230.0,González,Asistente,1242.0,2010-10-12,8000.0,3000.0,20.0,Ingeniería,Huerta
1,1231.0,Ramos,Vendedor,1235.0,2018-02-13,16000.0,3000.0,30.0,Ingeniería,Huerta
4,1234.0,Aldama,Vendedor,1235.0,2001-09-29,28500.0,2000.0,30.0,Ingeniería,Huerta
5,1235.0,Huerta,Administrador,1238.0,2009-05-16,24500.0,2000.0,30.0,Ingeniería,Huerta
16,1224.0,Santana,NaN,1235.0,2001-09-29,28500.0,2000,40.0,Ingeniería,Huerta
17,1225.0,Ramos,NaN,1238.0,2009-05-16,24500.0,2000,40.0,Ingeniería,Huerta
18,1227.0,Segura,NaN,1233.0,2005-05-05,29750.0,2000,20.0,Ingeniería,Huerta
19,1228.0,Hernández,NaN,0.0,2000-01-01,50000.0,2000,10.0,Ingeniería,Huerta
20,1229.0,Fuentes,NaN,1235.0,2006-02-24,15000.0,2000,40.0,Ingeniería,Huerta
27,1232.0,López,Vendedor,1235.0,2001-01-01,12500.0,5000.0,30.0,Ventas,Huerta
28,1233.0,Morales,Administrador,1238.0,2014-05-20,29750.0,0.0,20.0,Contabilidad,Huesca
29,1236.0,Rosillo,Administrador,1238.0,2017-03-13,30000.0,0.0,10.0,Operaciones,Huesca
30,1237.0,Segura,Analista,1233.0,2005-05-05,29750.0,0.0,20.0,Contabilidad,Morales
31,1238.0,Huesca,Presidente,1235.0,2000-01-01,50000.0,0.0,10.0,Operaciones,Huerta
32,1239.0,Rosales,Vendedor,1235.0,2006-02-24,15000.0,2000.0,30.0,Ventas,Huerta
33,1240.0,Benitez,Asistente,1237.0,2008-09-16,11000.0,0.0,20.0,Contabilidad,Segura
34,1241.0,Corona,Asistente,1235.0,2008-08-23,9500.0,0.0,30.0,Ventas,Huerta
35,1242.0,Domínguez,Analista,1233.0,2017-07-16,30000.0,0.0,20.0,Contabilidad,Morales
36,1248.0,Portales,Asistente,1236.0,2001-12-23,13000.0,0.0,10.0,Operaciones,Rosillo
37,1249.0,Moreno,Asistente,NaN,NaT,13000.0,0.0,NaN,Contabilidad,Huesca

In [10]:
# Función para consolidar información en strings
def join_unique(values):
    unique_vals = set(values.dropna())
    return ', '.join(map(str, unique_vals))

# Agrupar por 'Empleado' y agregar datos
df_final = df_general.groupby('Empleado').agg({
    'Nombre': 'first',  
    'Puesto': 'first', 
    'JefeNo': 'first',  
    'Fecha_Contratacion': 'first', 
    'Salario': 'max',  
    'Comisión': 'sum',  
    'DeptNo': 'first',  
    'Departamento': join_unique, 
    'Jefe': join_unique 
}).reset_index()

df_final

,Empleado,Nombre,Puesto,JefeNo,Fecha_Contratacion,Salario,Comisión,DeptNo,Departamento,Jefe
0,1224.0,Santana,None,1235.0,2001-09-29,28500.0,2000,40.0,Ingeniería,Huerta
1,1225.0,Ramos,None,1238.0,2009-05-16,24500.0,2000,40.0,Ingeniería,Huerta
2,1227.0,Segura,None,1233.0,2005-05-05,29750.0,2000,20.0,Ingeniería,Huerta
3,1228.0,Hernández,None,0.0,2000-01-01,50000.0,2000,10.0,Ingeniería,Huerta
4,1229.0,Fuentes,None,1235.0,2006-02-24,15000.0,2000,40.0,Ingeniería,Huerta
5,1230.0,González,Asistente,1242.0,2010-10-12,8000.0,3000.0,20.0,Ingeniería,Huerta
6,1231.0,Ramos,Vendedor,1235.0,2018-02-13,16000.0,3000.0,30.0,Ingeniería,Huerta
7,1232.0,López,Vendedor,1235.0,2001-01-01,12500.0,5000.0,30.0,Ventas,Huerta
8,1233.0,Morales,Administrador,1238.0,2014-05-20,29750.0,0.0,20.0,Contabilidad,Huesca
9,1234.0,Aldama,Vendedor,1235.0,2001-09-29,28500.0,2000.0,30.0,Ingeniería,Huerta
10,1235.0,Huerta,Administrador,1238.0,2009-05-16,24500.0,2000.0,30.0,Ingeniería,Huerta
11,1236.0,Rosillo,Administrador,1238.0,2017-03-13,30000.0,0.0,10.0,Operaciones,Huesca
12,1237.0,Segura,Analista,1233.0,2005-05-05,29750.0,0.0,20.0,Contabilidad,Morales
13,1238.0,Huesca,Presidente,1235.0,2000-01-01,50000.0,0.0,10.0,Operaciones,Huerta
14,1239.0,Rosales,Vendedor,1235.0,2006-02-24,15000.0,2000.0,30.0,Ventas,Huerta
15,1240.0,Benitez,Asistente,1237.0,2008-09-16,11000.0,0.0,20.0,Contabilidad,Segura
16,1241.0,Corona,Asistente,1235.0,2008-08-23,9500.0,0.0,30.0,Ventas,Huerta
17,1242.0,Domínguez,Analista,1233.0,2017-07-16,30000.0,0.0,20.0,Contabilidad,Morales
18,1248.0,Portales,Asistente,1236.0,2001-12-23,13000.0,0.0,10.0,Operaciones,Rosillo
19,1249.0,Moreno,Asistente,NaN,NaT,13000.0,0.0,NaN,Contabilidad,Huesca

In [11]:
# Carga de datos limpios y transformados a la base de datos
df_final.to_sql(name='data_frame_final', con=engine, if_exists='replace', index=False)
engine.dispose()